---
- hosts: all
  become: yes
  tasks:
  - name: i want to ping all hosts
    ping:
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
  - name: i want to start apche2 webserver
    service:
        name: apache2
        state: started
            
