---
- hosts: 172.31.41.196
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    tags: mygit  
    
  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget
      
    
