---
- hosts: 172.31.41.196
  become: yes
  tasks:
  - name: install git
    apt:
      name: gittt
      state: present
    tags: mygit  
    ignore_errors: yes
    
  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget
      
    
